spring:
  cloud:
    gateway:
      routes:
        - id: authorization-service
          uri: http://localhost:8081 # URL for Authorization Service
          predicates:
            - Path=/auth/**
          filters:
            - JwtAuthenticationFilter
        - id: notification-service
          uri: http://localhost:8082 # URL for Notification Service
          predicates:
            - Path=/notifications/**